### ISSUE TITLE
Hit test-pypi memory limit 

### ISSUE THREAD

**Issue by SimeonStoykovQC** [Quantco/pytsql#60]
There is a workflow that tries to upload the package to TestPyPI, and it [started failing with](https://github.com/Quantco/pytsql/actions/runs/3948464276/jobs/6760122674#step:4:132):
```
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
         Project size too large. Limit for project 'pytsql' total size is 10 GB.
         See https://test.pypi.org/help/#project-size-limit  
```

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/84503892/213386735-8b1d30bc-1a43-4121-b897-081c363b07b2.png">

This should not be critical.

We could consider:
1. Deleting what's already there to free up all space and deal with this when it happens again
2. Disable the workflow that uploads to testpypi

**Comment by ivergara** [comment]
I don't think it makes sense to upload to TestPyPI for every branch. Also, since I don't think anyone is actually making sure that whatever is pushed to TestPyPI is actually installable and working, it has no compelling purpose.

Maybe it'd make sense for tags that are meant to be released but then pushing to PyPI upon tag wouldn't make much sense.

My take, is just to remove the publish to TestPyPI altogether.
